library "cs_versions_cms_20250508"

// Generated on 2025-08-05T07:31:27.243850

define "Code System Versions":
{
  { "Code System": 'CDCREC', "Code System Version": '1.2', "Code System OID": '2.16.840.1.113883.6.238' },
  { "Code System": 'CDT', "Code System Version": '2023', "Code System OID": '2.16.840.1.113883.6.13' },
  { "Code System": 'CPT', "Code System Version": '2006', "Code System OID": '2.16.840.1.113883.6.12' },
  { "Code System": 'CPT', "Code System Version": '2020', "Code System OID": '2.16.840.1.113883.6.12' },
  { "Code System": 'CPT', "Code System Version": '2021', "Code System OID": '2.16.840.1.113883.6.12' },
  { "Code System": 'CPT', "Code System Version": '2024', "Code System OID": '2.16.840.1.113883.6.12' },
  { "Code System": 'CPT', "Code System Version": '2025', "Code System OID": '2.16.840.1.113883.6.12' },
  { "Code System": 'CVX', "Code System Version": '2024-12-16', "Code System OID": '2.16.840.1.113883.12.292' },
  { "Code System": 'HCPCS', "Code System Version": '2024', "Code System OID": '2.16.840.1.113883.6.285' },
  { "Code System": 'HCPCS', "Code System Version": '2025', "Code System OID": '2.16.840.1.113883.6.285' },
  { "Code System": 'HSLOC', "Code System Version": '2022', "Code System OID": '2.16.840.1.113883.6.259' },
  { "Code System": 'ICD10CM', "Code System Version": '2025', "Code System OID": '2.16.840.1.113883.6.90' },
  { "Code System": 'ICD10PCS', "Code System Version": '2025', "Code System OID": '2.16.840.1.113883.6.4' },
  { "Code System": 'LOINC', "Code System Version": '2.78', "Code System OID": '2.16.840.1.113883.6.1' },
  { "Code System": 'PresentOnAdmission', "Code System Version": '2021', "Code System OID": '2.16.840.1.113883.6.301.11' },
  { "Code System": 'RXNORM', "Code System Version": '2024-03', "Code System OID": '2.16.840.1.113883.6.88' },
  { "Code System": 'RXNORM', "Code System Version": '2025-01', "Code System OID": '2.16.840.1.113883.6.88' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2012-07', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2015-09', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2016-09', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2017-03', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2017-09', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2018-03', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2018-09', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2019-03', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2019-09', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2020-03', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2020-09', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2021-03', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2021-09', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2022-03', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2022-09', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2023-03', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2023-09', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2024-03', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SNOMEDCT', "Code System Version": '2024-09', "Code System OID": '2.16.840.1.113883.6.96' },
  { "Code System": 'SOP', "Code System Version": '9.2', "Code System OID": '2.16.840.1.113883.3.221.5' }
}

